#!/bin/bash

# =============================================================================
# TODO Telegram Bot - Automatic Installation Script for Ubuntu
# =============================================================================
# This script will:
# 1. Install Docker and Docker Compose (if not installed)
# 2. Clone the repository
# 3. Set up environment variables
# 4. Start the bot using Docker Compose
# =============================================================================

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
REPO_URL="https://github.com/datayouone02/Bot-test.git"
PROJECT_DIR="$HOME/todo-bot"
BOT_TOKEN="7599055445:AAF32gHj_4FDrNy1VZFnesB2--9k3rMqiuU"

# Functions
print_header() {
    echo -e "${BLUE}==============================================================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}==============================================================================${NC}"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ $1${NC}"
}

check_command() {
    if command -v "$1" &> /dev/null; then
        return 0
    else
        return 1
    fi
}

# Check if running as root
if [[ $EUID -eq 0 ]]; then
    print_warning "Running as root. This is not recommended for Docker."
    print_warning "Consider running as a regular user with sudo privileges."
fi

print_header "TODO Telegram Bot - Installation Script"

# Step 1: Update system packages
print_header "Step 1: Updating System Packages"
sudo apt-get update -y
print_success "System packages updated"

# Step 2: Install Docker if not present
print_header "Step 2: Installing Docker"
if check_command docker; then
    print_success "Docker is already installed: $(docker --version)"
else
    print_info "Installing Docker..."
    sudo apt-get install -y ca-certificates curl gnupg lsb-release
    sudo mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt-get update -y
    sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
    print_success "Docker installed successfully"
fi

# Step 3: Install Docker Compose if not present
print_header "Step 3: Checking Docker Compose"
if check_command docker-compose || docker compose version &> /dev/null; then
    print_success "Docker Compose is available"
else
    print_info "Installing Docker Compose..."
    sudo apt-get install -y docker-compose-plugin
    print_success "Docker Compose installed"
fi

# Step 4: Add user to docker group
print_header "Step 4: Configuring Docker Permissions"
if groups $USER | grep -q docker; then
    print_success "User is already in docker group"
else
    print_info "Adding user to docker group..."
    sudo usermod -aG docker $USER
    print_warning "You need to log out and back in for group changes to take effect"
    print_warning "Or run: newgrp docker"
fi

# Step 5: Clone repository
print_header "Step 5: Cloning Repository"
if [ -d "$PROJECT_DIR" ]; then
    print_warning "Directory $PROJECT_DIR already exists. Pulling latest changes..."
    cd "$PROJECT_DIR"
    git pull origin master
else
    print_info "Cloning repository from $REPO_URL..."
    git clone "$REPO_URL" "$PROJECT_DIR"
    cd "$PROJECT_DIR"
fi
print_success "Repository ready at $PROJECT_DIR"

# Step 6: Create .env file
print_header "Step 6: Configuring Environment Variables"
ENV_FILE="$PROJECT_DIR/.env"
if [ -f "$ENV_FILE" ]; then
    print_warning ".env file already exists. Backing up and creating new one..."
    cp "$ENV_FILE" "$ENV_FILE.backup.$(date +%s)"
fi

print_info "Creating .env file with your bot token..."
cat > "$ENV_FILE" << EOF
# Telegram Bot Configuration
# Auto-generated by install.sh on $(date)

# Your bot token from @BotFather
TOKEN=$BOT_TOKEN

# Your Telegram chat ID (get it by sending /get_id to the bot)
# Replace this with your actual chat ID
ADMIN_CHAT_ID=YOUR_CHAT_ID_HERE

# Database file path
DATABASE=tasks.db
EOF

print_success ".env file created at $ENV_FILE"
print_warning "IMPORTANT: You need to edit $ENV_FILE and replace YOUR_CHAT_ID_HERE with your actual Telegram chat ID"
print_info "To get your chat ID: message the bot and send /get_id command"

# Step 7: Create data directory
print_header "Step 7: Setting Up Data Directory"
mkdir -p "$PROJECT_DIR/data"
print_success "Data directory created"

# Step 8: Build and start the bot
print_header "Step 8: Building and Starting the Bot"
cd "$PROJECT_DIR"

print_info "Building Docker image..."
docker compose build

print_info "Starting the bot..."
docker compose up -d

print_success "Bot started successfully!"

# Step 9: Show status
print_header "Step 9: Verifying Installation"
sleep 3
docker compose ps
echo ""
docker compose logs --tail=20

print_header "Installation Complete!"
echo ""
print_info "The bot is now running in the background."
echo ""
print_info "Useful commands:"
echo -e "  ${YELLOW}cd $PROJECT_DIR${NC}"
echo -e "  ${YELLOW}docker compose logs -f${NC}     # View live logs"
echo -e "  ${YELLOW}docker compose restart${NC}     # Restart the bot"
echo -e "  ${YELLOW}docker compose down${NC}        # Stop the bot"
echo -e "  ${YELLOW}docker compose up -d${NC}       # Start the bot"
echo ""
print_warning "IMPORTANT: Don't forget to:"
echo -e "  1. Edit ${YELLOW}$ENV_FILE${NC} and set your ADMIN_CHAT_ID"
echo -e "  2. Restart the bot: ${YELLOW}docker compose restart${NC}"
echo ""
print_info "To get your chat ID:"
echo -e "  1. Start a chat with your bot on Telegram"
echo -e "  2. Send /get_id command"
echo -e "  3. Copy the chat ID and update .env file"
echo ""
print_success "Enjoy your TODO bot! 🎉"